=== Shaitz/xqueryCurriculaGAI/input/erasmus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:erasmus="http://www.erasmus.org" 
targetNamespace="http://www.erasmus.org" elementFormDefault="qualified" 
xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">

<xsd:element name="Erasmus" type="erasmus:ErasmusT"></xsd:element>

<xsd:complexType name="ErasmusT">
    <xsd:sequence>
        <xsd:element ref="erasmus:Candidate" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
</xsd:complexType>
    
<xsd:element name="Candidate" type="erasmus:CandidateT"/>

<xsd:complexType name="CandidateT">
    <xsd:sequence>
        <xsd:element name="Name" type="xsd:string"></xsd:element>
        <xsd:element name="Surname" type="xsd:string"></xsd:element>
        <xsd:element name="ContactInfo" type="erasmus:ContactT"></xsd:element>
        <xsd:element name="PassedCredits" type="xsd:int"></xsd:element>
        <xsd:sequence>
            <xsd:element ref="erasmus:LanguageLevel" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:sequence>
            <xsd:element ref="erasmus:Subject" maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
        <xsd:sequence>
            <xsd:element ref="erasmus:OriginUniversity"></xsd:element>
        </xsd:sequence>
        <xsd:sequence>
            <xsd:element ref="erasmus:DestinyUniversity"></xsd:element>
        </xsd:sequence>
    </xsd:sequence>
    <xsd:attribute name="ID" type="xsd:ID" use="required"/>
    <xsd:attribute name="ValidFrom" type="xsd:date" use="required"/>
    <xsd:attribute name="ValidTo" type="xsd:date" use="required"/>

    <xsd:assert test="@ValidFrom &lt; @ValidTo"/>
</xsd:complexType>

<xsd:element name="LanguageLevel" type="erasmus:LanguageLevelT"></xsd:element>

<xsd:complexType name="LanguageLevelT">
    <xsd:sequence>
        <xsd:element name="Level" type="xsd:string"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="Language" type="xsd:string" use="required"></xsd:attribute>
</xsd:complexType>

<xsd:element name="Subject" type="erasmus:SubjectT"></xsd:element>

<xsd:complexType name="SubjectT">
    <xsd:sequence>
        <xsd:element name="Name" type="xsd:string"></xsd:element>
        <xsd:element name="Credits" type="xsd:int"></xsd:element>
        <xsd:element name="Tutor" type="xsd:string" maxOccurs="unbounded"></xsd:element>
        <xsd:element name="Speciality" type="xsd:string"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="Term" type="erasmus:TermT" use="required"/>
</xsd:complexType>

<xsd:element name="OriginUniversity" type="erasmus:UniversityT"></xsd:element>
<xsd:element name="DestinyUniversity" type="erasmus:UniversityT"></xsd:element>

<xsd:complexType name="UniversityT">
    <xsd:sequence>
        <xsd:element name="Name" type="xsd:string"></xsd:element>
        <xsd:element name="Contact_email" type="xsd:string" maxOccurs="unbounded"></xsd:element>
        <xsd:element name="Country" type="erasmus:CountryT"></xsd:element>
    </xsd:sequence>
</xsd:complexType>

<xsd:complexType name="ContactT">
    <xsd:sequence>
        <xsd:element name="Telephone" type="erasmus:TelephoneT" minOccurs="0" maxOccurs="unbounded"></xsd:element>
        <xsd:element name="Email" type="xsd:string" minOccurs="0" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="TelephoneT">
	<xsd:restriction base="xsd:string">
        <xsd:pattern value="[0-9]{1,}"></xsd:pattern>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="CountryT">
	<xsd:restriction base="xsd:string">
        <xsd:pattern value="[A-Z]{2}"></xsd:pattern>
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="TermT">
    <xsd:restriction base="xsd:integer">
        <xsd:minInclusive value="1"/>
        <xsd:maxInclusive value="2"/>
    </xsd:restriction>
</xsd:simpleType>

</xsd:schema>

=== Shaitz/xqueryCurriculaGAI/input/ChrisMandel.xml
<?xml version="1.1"?>
<Erasmus xmlns="http://www.erasmus.org" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:fra="http://www.francia.org"
    xsi:schemaLocation="http://www.erasmus.org erasmus.xsd  http://www.francia.org francia.xsd">
    
    
    <Candidate ID="cm" ValidFrom="2022-01-01" ValidTo="2023-12-31"  xsi:type="fra:GPaisCandidateT">
        <Name>Chris</Name>
        <Surname>Mandel</Surname>
        <ContactInfo>
            <Telephone>456723896</Telephone>
            <Telephone>986231896</Telephone>
            <Email>chrismandel@gmail.com</Email>
            <Email>cmandel@student.co.uk</Email>
        </ContactInfo>
        <PassedCredits>150</PassedCredits>
        <LanguageLevel Language="English">
            <Level>C2</Level>
        </LanguageLevel>
        <LanguageLevel Language="French">
            <Level>B2</Level>
        </LanguageLevel>
        <Subject Term="1">
            <Name>Advanced Informatic Data Storage</Name>
            <Credits>12</Credits>
            <Tutor>Michelle Bach</Tutor>
            <Speciality>Software</Speciality>
        </Subject>
        <Subject Term="1">
            <Name>Web System Management</Name>
            <Credits>12</Credits>
            <Tutor>Francois Noir</Tutor>
            <Speciality>Software</Speciality>
        </Subject>
        <Subject Term="1">
            <Name>Graphic Interfaces and User Accessibility</Name>
            <Credits>6</Credits>
            <Tutor>Nichole Pierre</Tutor>
            <Speciality>Software</Speciality>
        </Subject>
        <OriginUniversity>
            <Name>Sherloch Holmes Univerity</Name>
            <Contact_email>shuLondon@hotmail.co.uk</Contact_email>
            <Country>EN</Country>
        </OriginUniversity>
        <DestinyUniversity>
            <Name>Paris National Informatic University</Name>
            <Contact_email>pniuParis@yahoo.fr</Contact_email>
            <Country>FR</Country>
        </DestinyUniversity>
        <fra:Accomodation>Private residence</fra:Accomodation>
    </Candidate>

</Erasmus>

=== Shaitz/xqueryCurriculaGAI/input/pepeGarcía.xml
<?xml version="1.0" encoding="UTF-8"?>
<Erasmus xmlns="http://www.erasmus.org" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:eresp="http://www.erasmusEsp.org"
    xsi:schemaLocation="http://www.erasmus.org erasmus.xsd http://www.erasmusEsp.org espania.xsd">
    
<Candidate xsi:type="eresp:alumnoConEstudios" ID="ESP1" ValidFrom="2000-01-01" ValidTo="2000-02-02">
    <Name>Pepe</Name>
    <Surname>García</Surname>
    <ContactInfo>
        <Email>pepes@gmail.com</Email>
    </ContactInfo>
    <PassedCredits>60</PassedCredits>
    <LanguageLevel Language="English">
        <Level>B2</Level>
    </LanguageLevel>
    <Subject Term="1">
        <Name>Economy</Name>
        <Credits>6</Credits>
        <Tutor>Laurent Laurent</Tutor>
        <Speciality></Speciality>
    </Subject>
    <Subject Term="1">
        <Name>Neural Networks</Name>
        <Credits>6</Credits>
        <Tutor>Pierre Thomas</Tutor>
        <Speciality>Computer Science</Speciality>
    </Subject>
    <Subject Term="2">
        <Name>Artificial Intelligence</Name>
        <Credits>6</Credits>
        <Tutor>Michael Petit</Tutor>
        <Speciality>Computer Science</Speciality>
    </Subject>
    <Subject Term="2">
        <Name>Big Data</Name>
        <Credits>6</Credits>
        <Tutor>Roux Durand</Tutor>
        <Speciality>Computer Science</Speciality>
    </Subject>
    <OriginUniversity xsi:type="eresp:universidadEspania">
        <Name>Universidad del País Vasco</Name>
        <Contact_email>upv@ehu.es</Contact_email>
        <Country>ES</Country>
        <eresp:Province>País Vasco</eresp:Province>
    </OriginUniversity>
    <DestinyUniversity>
        <Name>University of Paris</Name>
        <Contact_email>uop@uop.fr</Contact_email>
        <Country>FR</Country>
    </DestinyUniversity>
    <eresp:extras>
        <eresp:UniversidadPrevia>
            <Name>Universidad de Deusto</Name>
            <Contact_email>deusto@deusto.com</Contact_email>
            <Country>ES</Country>
            <eresp:Province>País Vasco</eresp:Province>
        </eresp:UniversidadPrevia>
        <eresp:Hobbies>
            <eresp:Hobby>Programar</eresp:Hobby>
            <eresp:Hobby>Echar la siesta</eresp:Hobby>
        </eresp:Hobbies>
    </eresp:extras>
</Candidate>
</Erasmus>
